// Icon components wrapper for consistent usage across the app
import React from 'react';
import { Feather, MaterialCommunityIcons, Ionicons } from '@expo/vector-icons';

// Re-export commonly used icons with consistent naming
export const Recycle = (props: any) => <MaterialCommunityIcons name="recycle" {...props} />;
export const Scan = (props: any) => <MaterialCommunityIcons name="barcode-scan" {...props} />;
export const ScanLine = (props: any) => <Ionicons name="scan-outline" {...props} />;
export const TrendingUp = (props: any) => <Feather name="trending-up" {...props} />;
export const Trophy = (props: any) => <Ionicons name="trophy" {...props} />;
export const User = (props: any) => <Feather name="user" {...props} />;
export const Home = (props: any) => <Feather name="home" {...props} />;
export const Mail = (props: any) => <Feather name="mail" {...props} />;
export const Lock = (props: any) => <Feather name="lock" {...props} />;
export const Eye = (props: any) => <Feather name="eye" {...props} />;
export const EyeOff = (props: any) => <Feather name="eye-off" {...props} />;
export const ArrowRight = (props: any) => <Feather name="arrow-right" {...props} />;
export const AlertCircle = (props: any) => <Feather name="alert-circle" {...props} />;
export const Sparkles = (props: any) => <Ionicons name="sparkles" {...props} />;
export const Flame = (props: any) => <Ionicons name="flame" {...props} />;
export const Target = (props: any) => <Feather name="target" {...props} />;
export const ChevronRight = (props: any) => <Feather name="chevron-right" {...props} />;
export const Leaf = (props: any) => <Ionicons name="leaf" {...props} />;
export const Droplets = (props: any) => <Ionicons name="water" {...props} />;
export const Wind = (props: any) => <Feather name="wind" {...props} />;
export const Camera = (props: any) => <Feather name="camera" {...props} />;
export const Image = (props: any) => <Feather name="image" {...props} />;
export const Zap = (props: any) => <Feather name="zap" {...props} />;
export const Check = (props: any) => <Feather name="check" {...props} />;
export const X = (props: any) => <Feather name="x" {...props} />;
export const Settings = (props: any) => <Feather name="settings" {...props} />;
export const LogOut = (props: any) => <Feather name="log-out" {...props} />;
export const Award = (props: any) => <Feather name="award" {...props} />;
export const Calendar = (props: any) => <Feather name="calendar" {...props} />;
export const Clock = (props: any) => <Feather name="clock" {...props} />;
export const Download = (props: any) => <Feather name="download" {...props} />;
export const Share = (props: any) => <Feather name="share-2" {...props} />;
export const Bell = (props: any) => <Feather name="bell" {...props} />;
export const HelpCircle = (props: any) => <Feather name="help-circle" {...props} />;
export const Shield = (props: any) => <Feather name="shield" {...props} />;
export const Globe = (props: any) => <Feather name="globe" {...props} />;
export const Users = (props: any) => <Feather name="users" {...props} />;
export const BarChart = (props: any) => <Feather name="bar-chart-2" {...props} />;
export const PieChart = (props: any) => <Feather name="pie-chart" {...props} />;
export const Activity = (props: any) => <Feather name="activity" {...props} />;
export const Star = (props: any) => <Feather name="star" {...props} />;
export const Heart = (props: any) => <Feather name="heart" {...props} />;
export const Plus = (props: any) => <Feather name="plus" {...props} />;
export const Minus = (props: any) => <Feather name="minus" {...props} />;
export const RefreshCw = (props: any) => <Feather name="refresh-cw" {...props} />;
export const Filter = (props: any) => <Feather name="filter" {...props} />;
export const Search = (props: any) => <Feather name="search" {...props} />;
export const MoreVertical = (props: any) => <Feather name="more-vertical" {...props} />;
export const Edit = (props: any) => <Feather name="edit-2" {...props} />;
export const Trash2 = (props: any) => <Feather name="trash-2" {...props} />;
export const Info = (props: any) => <Feather name="info" {...props} />;
export const ExternalLink = (props: any) => <Feather name="external-link" {...props} />;
